# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Echovault < Formula
  desc ""
  homepage "https://github.com/EchoVault/EchoVault"
  version "0.1.0"

  on_macos do
    url "https://github.com/EchoVault/EchoVault/releases/download/v0.1.0/EchoVault_Darwin_all.tar.gz"
    sha256 "848b11448308a9cb8a6564aac25ce51207b8623b8a32ea13b3e96b250f3bb616"

    def install
      bin.install "EchoVault"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EchoVault/EchoVault/releases/download/v0.1.0/EchoVault_Linux_arm64.tar.gz"
      sha256 "acc3bcd80eb996b8723aa7216dc54119ecfa50e038ecd421c3913ed87b22050a"

      def install
        bin.install "EchoVault"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/EchoVault/EchoVault/releases/download/v0.1.0/EchoVault_Linux_x86_64.tar.gz"
      sha256 "8c924d3a4037899033c19383ce02b1eb264390bde9fdfa2bd74ac0f0a0fc62f9"

      def install
        bin.install "EchoVault"
      end
    end
  end
end
