# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchovaultCli < Formula
  desc ""
  homepage "https://github.com/EchoVault/EchoVault-CLI"
  version "0.1.0"

  on_macos do
    url "https://github.com/EchoVault/EchoVault-CLI/releases/download/v0.1.0/EchoVault-CLI_Darwin_all.tar.gz"
    sha256 "defe3f371e15028842e9ffb96962e0d39d31ce26b096f11abf2d8442066cb23c"

    def install
      bin.install "EchoVault-CLI"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EchoVault/EchoVault-CLI/releases/download/v0.1.0/EchoVault-CLI_Linux_arm64.tar.gz"
      sha256 "294fe693f629253fc85aa7a2e17570c52133b2615c1255d2cb5970c7e46004c2"

      def install
        bin.install "EchoVault-CLI"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/EchoVault/EchoVault-CLI/releases/download/v0.1.0/EchoVault-CLI_Linux_x86_64.tar.gz"
      sha256 "c7250c8a6bba7c334ff00e76de38a06001d3a73c380e13209c657606664ca118"

      def install
        bin.install "EchoVault-CLI"
      end
    end
  end
end
