# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Echovault < Formula
  desc ""
  homepage "https://github.com/EchoVault/EchoVault"
  version "0.12.0"

  on_macos do
    url "https://github.com/EchoVault/EchoVault/releases/download/v0.12.0/EchoVault_Darwin_all.tar.gz"
    sha256 "8c30c0cdfd498e2767ed10e2e23274d00151dea9c9aa8586d1ee04c28786ab6e"

    def install
      bin.install "EchoVault"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/EchoVault/releases/download/v0.12.0/EchoVault_Linux_x86_64.tar.gz"
        sha256 "5205cc0446c60540a332d333404e11f357b991b9694ff8bf299657c0b2f86f9f"

        def install
          bin.install "EchoVault"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/EchoVault/releases/download/v0.12.0/EchoVault_Linux_arm64.tar.gz"
        sha256 "fbcd7cac8522d18aac01a852df004693f12060724f95ec5ecbddc7b138651b80"

        def install
          bin.install "EchoVault"
        end
      end
    end
  end
end
