# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchovaultCli < Formula
  desc ""
  homepage "https://github.com/EchoVault/EchoVault-CLI"
  version "0.1.0"

  on_macos do
    url "https://github.com/EchoVault/EchoVault-CLI/releases/download/v0.1.0/EchoVault-CLI_Darwin_all.tar.gz"
    sha256 "5998b7aef783d7407f8a985c08e26348db9fedb96f1c7bb0372d5a5f71bf00db"

    def install
      bin.install "EchoVault-CLI"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EchoVault/EchoVault-CLI/releases/download/v0.1.0/EchoVault-CLI_Linux_arm64.tar.gz"
      sha256 "3a77a9ccd011bcdf8be28b93ca0f0203ec1c5ed12d37fbdbe9d359ab945cdfc6"

      def install
        bin.install "EchoVault-CLI"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/EchoVault/EchoVault-CLI/releases/download/v0.1.0/EchoVault-CLI_Linux_x86_64.tar.gz"
      sha256 "bca2159578fe41fdcbd60a247e49469c0637c458ede3af8aa9bb3892f43f2b6a"

      def install
        bin.install "EchoVault-CLI"
      end
    end
  end
end
