# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sugardb < Formula
  desc ""
  homepage "https://github.com/EchoVault/SugarDB"
  version "0.13.1"

  on_macos do
    url "https://github.com/EchoVault/SugarDB/releases/download/v0.13.1/SugarDB_Darwin_all.tar.gz"
    sha256 "87f3e5560daeb25e55fd819cf61ac78adcac7270e5c78aaab3146e7ea11c7eb7"

    def install
      bin.install "SugarDB"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/SugarDB/releases/download/v0.13.1/SugarDB_Linux_x86_64.tar.gz"
        sha256 "da40bd6c21fcb8f732fef14ca44872a5cac7ce6f67b443e60c54511e96344e11"

        def install
          bin.install "SugarDB"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/SugarDB/releases/download/v0.13.1/SugarDB_Linux_arm64.tar.gz"
        sha256 "46061d9631d1d659ae6a23ea0276f843cf1a78127c5acf78a65ccf7a3579844e"

        def install
          bin.install "SugarDB"
        end
      end
    end
  end
end
