# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sugardb < Formula
  desc ""
  homepage "https://github.com/EchoVault/SugarDB"
  version "0.14.0"

  on_macos do
    url "https://github.com/EchoVault/SugarDB/releases/download/v0.14.0/SugarDB_Darwin_all.tar.gz"
    sha256 "a05617702691b7288e24831324c3ba6d0a0139859030fbb862efd2c23581822f"

    def install
      bin.install "SugarDB"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/SugarDB/releases/download/v0.14.0/SugarDB_Linux_x86_64.tar.gz"
        sha256 "3007a22b3b591035fa3e30c1ddd5cba1bf5f8791d6c624c949d3ce0bbc333dba"

        def install
          bin.install "SugarDB"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/SugarDB/releases/download/v0.14.0/SugarDB_Linux_arm64.tar.gz"
        sha256 "7bc14cbee49140e0e7da8ad276558349c8a25760ac2a435d1443fab9c2bbaf21"

        def install
          bin.install "SugarDB"
        end
      end
    end
  end
end
