# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sugardb < Formula
  desc ""
  homepage "https://github.com/EchoVault/SugarDB"
  version "0.15.0"

  on_macos do
    url "https://github.com/EchoVault/SugarDB/releases/download/v0.15.0/SugarDB_Darwin_all.tar.gz"
    sha256 "fc7fb2dae6b9388078c80d81fe10c1bebe9cc880ab0a5ddf66332287711360ba"

    def install
      bin.install "SugarDB"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/SugarDB/releases/download/v0.15.0/SugarDB_Linux_x86_64.tar.gz"
        sha256 "8b6ff1a99d41c6a70835617f9a71c5708009ef9956481c392c06705342faa1ce"

        def install
          bin.install "SugarDB"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/EchoVault/SugarDB/releases/download/v0.15.0/SugarDB_Linux_arm64.tar.gz"
        sha256 "b9625168a06a5d8c7c103e1586e7ac67cc9912134adb0f5bc0010bb944573853"

        def install
          bin.install "SugarDB"
        end
      end
    end
  end
end
